# MySQL properties
bd.driver=com.mysql.cj.jdbc.Driver
bd.url=jdbc:mysql://localhost:3306/zadacha_2_3_1?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
bd.username=root
bd.password=1234

# Hibernate properties

hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

#create, update